### ISSUE TITLE
Compile fails when using SceneTree with GpuParticles3D

### ISSUE THREAD

**Issue by Vodurden** [Cat-Lips/GodotSharp.SourceGenerators#55]
## Problem

Thanks for the really useful library! Unfortunately I think I've run into an issue with the `SceneTree` generator.

`[SceneTree]` seems to generate a property / field with the type `GPUParticles3D`, but the actual C# type is `GpuParticles3D`  (presumably because of [this](https://github.com/godotengine/godot/pull/69547))

This fails to build with
```
CS0234: The type or namespace name 'GPUParticles3D' does not exist in the namespace 'Godot' (are you missing an assembly reference?) .../GodotSharp.SourceGenerators/GodotSharp.SourceGenerators.SceneTreeExtensions.SceneTreeSourceGenerator/MyScene.g.cs
```

I imagine this will affect other similar classes where the C# type name doesn't match the casing conventions stored in the `.tscn` file.

## Example

If I have a scene like this:

```
MyScene (Node)
+- Particles (GPUParticles3D)
```

And I have a script like this:

```csharp
[SceneTree]
public partial class MyScene : Node {}
```

This will generate (snippet):

```csharp
[EditorBrowsable(EditorBrowsableState.Never)]
private Godot.GPUParticles3D _Particles;

public Godot.GPUParticles3D Particles => _Particles ??= node.GetNodeOrNull<Godot.GPUParticles3D>("Particles");
```

The generated code is invalid because it uses `GPUParticles3D`, but the GodotSharp type is `GpuParticles3D`. This causes the build to fail with:
```
CS0234: The type or namespace name 'GPUParticles3D' does not exist in the namespace 'Godot' (are you missing an assembly reference?) .../GodotSharp.SourceGenerators/GodotSharp.SourceGenerators.SceneTreeExtensions.SceneTreeSourceGenerator/MyScene.g.cs
```

## Possible Fixes

It seems like the naming transaction for C# is done in the [get_base_class_name C++ function](https://github.com/raulsntos/godot/blob/4a0160241fd0c1e874e297f6b08676cf0761e5e8/modules/mono/csharp_script.cpp#L347-L353), which ultimately uses the [`pascal_to_pascal_case` function](https://github.com/raulsntos/godot/blob/79de2eaae7fb3bb8f13031ac2ec9b19128b6f471/modules/mono/utils/naming_utils.cpp#L145-L194). 

There also seems to be a few hardcoded overrides [here](https://github.com/raulsntos/godot/blob/79de2eaae7fb3bb8f13031ac2ec9b19128b6f471/modules/mono/utils/naming_utils.cpp#L44-L86). 

I'm guessing we can't directly call the bindgen functions, so I imagine we'd need to title case the functions and then apply the same set of hardcoded overrides?

**Comment by Vodurden** [comment]
Oh it looks like `GodotSharp` does have a [native function exposed](https://github.com/godotengine/godot/blob/7abe0c6014022874378cb64a11b26b0f0f178324/modules/mono/glue/GodotSharp/GodotSharp/Core/StringExtensions.cs#L353-L359). Not sure if we can access it in this source generator though :thinking:

**Comment by Cat-Lips** [comment]
Hi Vodurden.

Thanks for finding this and for investigating.
Pull request contains tests & changes required to fix the problem.
Much appreciated if you could test it your end before we release :)
I've uploaded a pre-release nuget and also a config you can use to easily add local packages via visual studio if that helps.

Caveats:
 - Obviously anything added can slow down compilation.  I always try to limit O(n) searches, but we have a few here.  Not too noticeable, but everything adds up.  If it becomes an issue, I might be able to cache the results.
 - Obviously the fix doesn't deal with multiple types or namespaces that have the same name.  Since we know we're only using it for GodotSharp, that should be ok for now.

Cheers.

[GodotSharp.SourceGenerators.2.3.4-240424-1056.Release.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/15084613/GodotSharp.SourceGenerators.2.3.4-240424-1056.Release.zip)

[nuget.config.zip](https://github.com/Cat-Lips/GodotSharp.SourceGenerators/files/15084635/nuget.config.zip)

**Comment by Vodurden** [comment]
I tried this locally and it works! Thanks for resolving this so quickly :slightly_smiling_face:
