### ISSUE TITLE
[Proposal] Generate public static InputMap instead of adding [InputMap] attribute to every script.

### ISSUE THREAD

**Issue by valkyrienyanko** [Cat-Lips/GodotSharp.SourceGenerators#68]
Why? Because lets say I have a input called "dash", this would generate Dash field in the script I added [InputMap] to and would conflict with my Dash() method name.

I feel `InputMap.Dash` is much more readable than just `Dash`.

This would mean no more needing to add [InputMap] attribute to every script. All the inputs would be kept track of in 
```cs
public static class InputMap
{
    public readonly static StringName Dash = "dash";
    // more inputs here
}
```

**Comment by Cat-Lips** [comment]
Ah.  I've always used [InputMap] on a separate class/node, so unfortunately didn't think of naming conflicts when used in a game script.

```
    [InputMap]
    public partial class MyInput : Node
    {
        ... // eg, Track mouse motion if needed outside of input handlers
    }
```

It can also be static if no node behaviour required:

```
    [InputMap]
    public static partial class MyInput {}
```

I had thought about making it an always present, generator defined class, but it's probably better to let the consumer decide what to name it since Godot.InputMap already exists (or if they want it at all!).

**Comment by valkyrienyanko** [comment]
Thank you this is exactly what I wanted!

```cs
using Godot;

namespace Template;

[InputMap]
public static partial class InputActions
{
    // Source generator generates the inputs in different partial
    // Use like so: InputActions.MoveLeft, InputActions.MoveRight, etc
}
```

**Comment by Cat-Lips** [comment]
Cool, ta :)
