### ISSUE TITLE
Godot Warning in Console: 'X' hides inherited member 'Y'. Use the new keyword if hiding was intended.

### ISSUE THREAD

**Issue by valkyrienyanko** [Cat-Lips/GodotSharp.SourceGenerators#70]
## Screenshots
![Untitled](https://github.com/user-attachments/assets/ca3c820f-93bf-4e07-a214-d0e41bd5fb80)

![Untitled](https://github.com/user-attachments/assets/cbad0bdd-b5ee-4dfd-a046-2edaf5013031)

## Steps to Reproduce
1. Install `Godot v4.3.stable.mono.official [77dcf97d8]`
2. `git clone --recursive https://github.com/ValksGodotTools/Template`
3. Make sure you are on commit `5c3f23fc2128dbdf5991398c9e5fc014da407095` in case I changed the code later
4. Set the main startup scene to `res://Sandbox/Inventory/InventorySandbox.tscn`
5. Run the game. Close the game.
6. Notice the warnings in the console.

## Potential Solution
Add `new` keyword to all generated members in the source generator.

**Comment by valkyrienyanko** [comment]
As a temporary workaround I've added `<NoWarn>CS0108</NoWarn>` to my `.csproj`.

**Comment by Cat-Lips** [comment]
Hi Valk.  Thanks for picking this up.

For the SceneTree attribute, I can see that the script inherits but the scene does not.  Not sure if this is intentional.  If the scene were to also inherit, this would no longer be a problem since the conflicting properties would be generated for the base class and not the derived class.  If it is intentional, then we're saying that the scenes & nodes are different and could deviate, but the code just happens to be the same, which probably means the base class should not be referring to said nodes, otherwise things will go much awry.  So in this case I think we've been lucky in that the warning has picked up something in the tscn structure that we should probably change.  (If not let's talk more...)

For the OnInstantiate attribute, we definitely need a new operator and either disable warning about new not being required (like Godot does for it's signal/method/property name files), or a proper symbol check to see if it's needed.  (Hmph, for that matter, could just disable warning about new operator being required - I don't think it actually does anything except warn of possible OO programming error...)

If you agree with all this, I'll make branch for OnInstantiate bug fix and leave SceneTree as is.

Cheers.

**Comment by Cat-Lips** [comment]
(Also noticed that the overridden _Ready in derived class doesn't call base._Ready.  If it helps, the GodotOverride attribute handles this for you, minimising potential errors.  The base call can be skipped with an attribute parameter if needed.)

**Comment by valkyrienyanko** [comment]
I tried changing the _Ready method in CursorItemContainer to be OnReady with [GodotOverride] (I tried with both replace on and off) and both produced same error.

I don't even want to use [GodotOverride] just because its not my style. I like writing out the whole public override void _Ready() and base._Ready().

I feel like I missed something you said that was important. Something about "I can see that the script inherits but the scene does not". 

I just don't get it sorry.

I don't mind just having <NoWarn>CS0108</NoWarn> in my .csproj.

![Untitled](https://github.com/user-attachments/assets/84a16afe-4120-48f7-8df9-aa2117b7230a)
![Untitled](https://github.com/user-attachments/assets/c151095c-0df6-4524-9fbd-80dcbf41e26f)
![Untitled](https://github.com/user-attachments/assets/59d208e7-2afc-43a2-a6fa-960f761b0e1d)

Code in images above references the following updated commit `a801101e9c5e30e072dea9226a8f6db84febb893` for Template repo.

**Comment by Cat-Lips** [comment]
> I tried changing the _Ready method in CursorItemContainer to be OnReady with [GodotOverride] (I tried with both replace on and off) and both produced same error.

For Godot 4 (due to source generators) you need to have a partial declaration and the OnReady method would be private or protected (virtual if inheriting), but as you say, not your style so no worries :)

> I feel like I missed something you said that was important. Something about "I can see that the script inherits but the scene does not".

By scene I meant tscn.  (So in editor, right click ItemContainer.tscn -> New Inherited Scene, save as CursorItemContainer.  Also in editor, remove ItemContainer.cs script, add CursorItemContainer.cs which inherits from ItemContainer.cs).  You can then update (override) properties in the inspector, add new nodes anywhere in the heirarchy, but can't change the inherited node names or structure (so any code in ItemContainer.cs that uses them won't break).

**Comment by valkyrienyanko** [comment]
Thanks I knew the "New Inherited" button was a thing but I never knew what it actually was used for. Now I know thanks to you. Everything works, no more warning. Thank you.
