### ISSUE TITLE
Attempt to support scn

### ISSUE THREAD

**Issue by youfch** [Cat-Lips/GodotSharp.SourceGenerators#89]
I found that tscn works well, but it does not seem to support scn, I am not very familiar with source code generation, can I have the opportunity to support scn?

**Comment by Cat-Lips** [comment]
scn is the binary format so would be tricky.  tscn is the text format that gets compiled to scn on export.

Can I ask why you're using scn?

**Comment by youfch** [comment]
scn is smaller than tscn, and now the project is great

> scn 是二进制格式，所以会很棘手。tscn 是在导出时编译为 scn 的文本格式。
> 
> 我能问问你为什么使用 scn 吗？

**Comment by Cat-Lips** [comment]
Your exported project should be the same size regardless of whether you use scn or tscn in development (since tscn is compiled to scn and not included in the export), so I'm assuming you mean the size of your git repository?  If so, you would want to use tscn anyway because the constant changing of binary files will greatly increase the size (ie, history) of your repository and make it difficult to see what has changed.  This is why tscn exists and is preferred over scn.  Also, the size of your binary assets (models, images, etc) will take much more space than any source/tscn/text files.  So whilst yes, technically we could support scn (by reading the scene into Godot, converting to tscn then parsing as normal, thus increasing compilation time), I'm not sure that's something that should be encouraged.  (Please correct me if I'm wrong - we're all still learning!)

**Comment by youfch** [comment]
I found that using scn is much faster than tscn when debugging the game. Your answer above is can I use tscn to generate code and then convert it to scn debugging

**Comment by youfch** [comment]
It's hard not to do it, now this nuget is great

**Comment by Cat-Lips** [comment]
> I found that using scn is much faster than tscn when debugging the game.
Yes, scn is probably faster, but again, load time of content would be the main bottleneck.

> Your answer above is can I use tscn to generate code and then convert it to scn debugging
Just use tscn.  The editor will convert to scn when you export your game.

> It's hard not to do it, now this nuget is great
Ok, ta.  We can always revisit if required.
